# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: IamMC # ex. I m Chuan
subtitle: 瞧瞧我都干了些什么！
name: McAce # ex. DONGChuan
email: n0tmc8ce@gmail.com
#location: My location # ex. Nice, France
#company: MyCompany
#company_url: my_company_website
github_url: https://github.com/mcace # ex. https://github.com/DONGChuan
github_username: mcace # ex. DONGChuan
description: 这是我的博客
favicon: favicon.png # Image must be in assets/images
repository: mcace/mcace.github.io # ex. DONGChuan/DONGChuan.github.io

# The base hostname & protocol for your site
# For local test, please use http://localhost:4000
# For production, use your github page url. ex. http://dongchuan.github.io
url: http://mcace.github.io

## Gem
gems:
  - jekyll-paginate
  - jekyll-geo-pattern
  - rouge
  - kramdown
  - jekyll-github-metadata

# Build settings
markdown: kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"

source:      .
destination: ./_site

quiet:    false
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"


kramdown:
  input: GFM
  enable_coderay: true

# Disque
#disque: my_disque_settings # ex. httpdongchuangithubio.disqus.com

# Pagination
paginate: 10
paginate_path: 'page:num'

# Navigation. If you do not like these modules, just remove them :D
navs:
  -
    href: /
    label: 首页

  -
    href: /open-source
    label: 我的码

  -
    href: /blog
    label: 博文

  -
    href: /about
    label: 我

#front-page-subtitle-navs:
#  -
#    href: /github/github-pages/jekyll/2018/06/17/use-github-pages.html
#    label: Jekyll&Github Pages搭建博客


# Sidebar to show popular repo
side_bar_repo_limit: 5 # Number of repos to show

# Google Analytics
#analytics :
#  provider : google
#  google :
#      tracking_id : 'tracking_id'  # ex. UA-72165600-X


# For about.html. Fell free to create your own!
skill_software_keywords: [Java, MySQL]
skill_j2ee_keywords: [Spring, Struct, Hibernet, MyBatis, JSP]
skill_web_keywords: [HTML, CSS, JS, JQuery, Ajax, MongoDB]
#skill_mobile_app_keywords: [Android, Sketch UI Desgin]
